# Generated by Django 3.1 on 2021-09-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='note_text',
            field=models.TextField(),
        ),
    ]
